#datasource
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.22:3306/blogs?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username:
    password:


    # 第三方连接池需要设置为 always
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema/*.sql

#log
logging:
  file:
    path:
    name:
  level:
    root: INFO
    com:
      zbw: DEBUG
