#datasource
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fame-mysql:3306/fame?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema/*.sql
#log
logging:
  level:
    root: INFO
    com:
      designre: INFO
  file:
    name: log/blog.log